### ISSUE TITLE
您好，请问运行报错是什么原因

### ISSUE THREAD

**Issue by chadwang2012** [anonymous0618/MB-GMN#4]
我是Python 3.6.6 tensorflow 1.14.0

没有对代码作任何修改，直接运行python labcode.py时如下报错，请问这是什么原因呢？

tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMMBatched launch failed : a.shape=[6520,1,96], b.shape=[6520,1,32], m=96, n=32, k=1, batch_size=6520
	 [[{{node gradients/matmul_74_grad/MatMul_1}}]]
	 [[Adam/update/_148]]
  (1) Internal: Blas xGEMMBatched launch failed : a.shape=[6520,1,96], b.shape=[6520,1,32], m=96, n=32, k=1, batch_size=6520
	 [[{{node gradients/matmul_74_grad/MatMul_1}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labcode.py", line 344, in <module>
    recom.run()
  File "labcode.py", line 50, in run
    reses = self.trainEpoch()
  File "labcode.py", line 246, in trainEpoch
    res = self.sess.run(target, feed_dict=feed_dict, options=config_pb2.RunOptions(report_tensor_allocations_upon_oom=True))
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMMBatched launch failed : a.shape=[6520,1,96], b.shape=[6520,1,32], m=96, n=32, k=1, batch_size=6520
	 [[node gradients/matmul_74_grad/MatMul_1 (defined at labcode.py:198) ]]
	 [[Adam/update/_148]]
  (1) Internal: Blas xGEMMBatched launch failed : a.shape=[6520,1,96], b.shape=[6520,1,32], m=96, n=32, k=1, batch_size=6520
	 [[node gradients/matmul_74_grad/MatMul_1 (defined at labcode.py:198) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node gradients/matmul_74_grad/MatMul_1:
 ExpandDims_29 (defined at labcode.py:151)

Input Source operations connected to node gradients/matmul_74_grad/MatMul_1:
 ExpandDims_29 (defined at labcode.py:151)

Original stack trace for 'gradients/matmul_74_grad/MatMul_1':
  File "labcode.py", line 344, in <module>
    recom.run()
  File "labcode.py", line 38, in run
    self.prepareModel()
  File "labcode.py", line 198, in prepareModel
    self.optimizer = tf.train.AdamOptimizer(learningRate).minimize(self.loss, global_step=globalStep)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 403, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 1511, in _BatchMatMulV2
    grad_y = math_ops.matmul(x, grad, adjoint_a=True, adjoint_b=False)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2609, in matmul
    return batch_mat_mul_fn(a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/home/wangchao/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1677, in batch_mat_mul_v2
    "BatchMatMulV2", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'matmul_74', defined at:
  File "labcode.py", line 344, in <module>
    recom.run()
[elided 0 identical lines from previous traceback]
  File "labcode.py", line 38, in run
    self.prepareModel()
  File "labcode.py", line 186, in prepareModel
    preds = self.predict(src, tgt)
  File "labcode.py", line 166, in predict
    return self._predict(src_ulat, src_ilat, predParams) * args.mult
  File "labcode.py", line 152, in _predict
    predEmbed = Activate(predEmbed @ params['w1'] + params['b1'], self.actFunc)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2609, in matmul
    return batch_mat_mul_fn(a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1677, in batch_mat_mul_v2
    "BatchMatMulV2", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by akaxlh** [comment]
你好，我重新下载这份代码到本机上进行了测试，没有出现这个问题。我发现了下面几个可能的解决方案，可以尝试一下：
https://blog.csdn.net/bonjourdeutsch/article/details/103334810
https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed
https://blog.csdn.net/SDFJXVC/article/details/113768943

**Comment by chadwang2012** [comment]
> 你好，我重新下载这份代码到本机上进行了测试，没有出现这个问题。我发现了下面几个可能的解决方案，可以尝试一下： https://blog.csdn.net/bonjourdeutsch/article/details/103334810 https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed https://blog.csdn.net/SDFJXVC/article/details/113768943

感谢您这么快的回复，我请朋友帮忙运行，在他的服务器上也是可以运行的，可能是我的配置出错了，我再排查一下。
